# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: img-download

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
          npm install
    - name: "download img"
      run: |
          npm run img
    - name: Commit report
      run: |
          date=$(date '+%Y-%m-%d %H:%M')
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "save archives at $date"
          git push
      env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        release_name: Release_NUMBER ${{ github.GITHUB_RUN_NUMBER }}
        draft: false
        prerelease: false

